<?php

/**
 * Implementation of hook_ctools_plugin_directory().
 *
 * It simply tells panels where to find the .inc files that define various
 * args, contexts, content_types. In this case the subdirectories of
 * ctools_plugin_example/panels are used.
 */
function panels_extra_layouts_ctools_plugin_directory($module, $plugin) {
  //  if ($module == 'panels_extra_layouts' && !empty($plugin)) {
    return "plugins/$plugin";
    //}
}
